export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const GET_ORDER_PRODUCTS_REQUEST = 'GET_ORDER_PRODUCTS_REQUEST'
export const GET_ORDER_PRODUCTS_SUCCESS = 'GET_ORDER_PRODUCTS_SUCCESS'
export const GET_ORDER_PRODUCTS_FAIL = 'GET_ORDER_PRODUCTS_FAIL'
export const GET_ORDER_PRODUCTS_RESET = 'GET_ORDER_PRODUCTS_RESET'

export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL'
