export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'

export const GET_ORDER_PRODUCTS_REQUEST = 'GET_ORDER_PRODUCTS_REQUEST'
export const GET_ORDER_PRODUCTS_SUCCESS = 'GET_ORDER_PRODUCTS_SUCCESS'
export const GET_ORDER_PRODUCTS_FAIL = 'GET_ORDER_PRODUCTS_FAIL'
